### ISSUE TITLE
Logging 3.2.0 Failed deploy due to update deployer image in template

### ISSUE THREAD

**Issue by xiazhao2015** [chunyunchen/scripts#2]
Error log:
http://pastebin.test.redhat.com/405892

Sentence in question:
oc get template logging-deployer-template -o yaml -n openshift | sed  '"'"'s/(image:\s._)logging-deployer(._)/logging-deployment/g'"'"' | oc apply -n openshift -f -

oc get template logging-deployer-template -o yaml -n openshift | sed  's/(image:\s._)logging-deployment(._)/\1logging-deployer\2/g' | oc apply -n openshift -f -

After disabled this function, 3.2.0 gets deployed successfully

**Comment by chunyunchen** [comment]
have fixed.
